
DOCS=../inst/doc/overview.html ../inst/doc/overview.pdf ../inst/doc/implementation.html ../Todo.html \
     ../inst/examples/JavaScriptCanvas/Rjs.R      ../inst/examples/JavaScriptCanvas/jsEg.R \
     ../inst/examples/SVG/svgDev.R      ../inst/examples/SVG/svgEg.R \

include ../../Config/GNUmakefile.Web

HTML_STYLESHEET=http://www.omegahat.org/OmegaTech.css



RD_FILES=$(wildcard ../man/*.Rd)
HTML_DOC_FILES=$(RD_FILES:%.Rd=docs/%.html)
htmlDocs: $(HTML_DOC_FILES)






